import { commonRouteNames } from '@survv/commons/core/routes/routes';

export const ROUTE_NAMES = Object.freeze({
  ...commonRouteNames,
  CUSTOMERS: 'ROUTE_CUSTOMERS',
  CUSTOMER_DETAILS: 'ROUTE_CUSTOMER_DETAILS',
  SIGN_IN: 'ROUTE_LOGIN',
  ONLINE_ORDERING_VENDOR_ONLINE_PROFILE: 'ROUTE_ONLINE_ORDERING_VENDOR_PROFILE',
  ONLINE_ORDERING_VENDOR_ONLINE_PROFILE_LIST:
    'ROUTE_ONLINE_ORDERING_VENDOR_LIST',
  ONLINE_ORDERING_VENDOR_ONLINE_PROFILE_CREATION:
    'ROUTE_ONLINE_ORDERING_VENDOR_PROFILE_CREATION',
  ONLINE_ORDERING_VENDOR_ONLINE_PROFILE_UPDATE:
    'ROUTE_ONLINE_ORDERING_VENDOR_PROFILE_UPDATE',
  ONLINE_ORDERING_CATALOGUE_CREATION: 'ONLINE_ORDERING_CATALOGUE_CREATION',
  ONLINE_ORDERING_CATALOGUE_DETAILS: 'ONLINE_ORDERING_CATALOGUE_DETAILS',
  ONLINE_ORDERING_CATALOGUE_UPDATE: 'ONLINE_ORDERING_CATALOGUE_UPDATE',
  ONLINE_ORDERING_CATALOGUE_ITEM_CREATION:
    'ONLINE_ORDERING_CATALOGUE_ITEM_CREATION',
  ONLINE_ORDERING_CATALOGUE_ITEM_UPDATE:
    'ONLINE_ORDERING_CATALOGUE_ITEM_UPDATE',
  ONLINE_ORDERING_CATALOGUE_ITEM_DETAILS:
    'ONLINE_ORDERING_CATALOGUE_ITEM_DETAILS',
  ONLINE_ORDERING_APPLICATION: 'ONLINE_ORDERING_APPLICATION',
  ONLINE_ORDERING_VENDOR_ONLINE_PROFILE_BRANCHES_LISTING:
    'ONLINE_ORDERING_BRANCHES_LISTING',
  ONLINE_ORDERING_VENDOR_ONLINE_PROFILE_BRANCHES_DETAILS:
    'ONLINE_ORDERING_BRANCHES_DETAILS',
  ONLINE_ORDERING_VENDOR_ONLINE_PROFILE_BRANCHES_CREATION:
    'ONLINE_ORDERING_BRANCHES_CREATION',
  ONLINE_ORDERING_VENDOR_ONLINE_PROFILE_BRANCHES_UPDATE:
    'ONLINE_ORDERING_BRANCHES_UPDATE',
  LIVE_OPS_ORDERS: 'LIVE_OPS_ORDERS',
  LIVE_OPS_ORDERS_OVERVIEW: 'LIVE_OPS_ORDERS_OVERVIEW',
  LIVE_OPS_ORDERS_LISTING: 'LIVE_OPS_ORDERS_LISTING',
  ORDERS_LIST: 'ORDERS_LIST',
  ORDER_DETAILS: 'ORDER_DETAILS',
  ERRAND_ORDER_DETAILS: 'ERRAND_ORDER_DETAILS',
  CAMPAIGNS_LIST: 'CAMPAIGNS_LIST',
  CAMPAIGN_CREATION: 'CAMPAIGN_CREATION',
  REFERRAL_LIST: 'REFERRAL_LIST',
  REFERRAL_SETUP: 'REFERRAL_SETUP',
  REFERRAL_REPORT: 'REFERRAL_REPORT',
  REFEREE_ORDERS_REPORT: 'REFEREE_ORDERS_REPORT',
  REFEREE_SUCCESSFUL_ORDERS_REPORT: 'REFEREE_SUCCESSFUL_ORDERS_REPORT',
  ERRANDS_CATEGORIES_LIST: 'ERRANDS_CATEGORIES_LIST',
  TAX_TIERS: 'TAX_TIERS',
  USERS_LIST: 'USERS_LIST',
  USERS_CREATION: 'USERS_CREATION',
  USERS_PROFILE_UPDATE: 'USERS_PROFILE_UPDATE',
  PUSH_NOTIFICATIONS: 'PUSH_NOTIFICATIONS',
  PUSH_NOTIFICATIONS_CREATION: 'PUSH_NOTIFICATIONS_CREATION',
});
