import { commonRouteNames } from '@survv/commons/core/routes/routes';

export const ROUTE_NAMES = Object.freeze({
  ...commonRouteNames,

  AGENT_ORDERS_LIST: 'ROUTE_AGENT_ORDERS_LIST',
  AGENT_ORDER_DETAILS: 'ROUTE_AGENT_ORDER_DETAILS',
  AGENT_ORDER_EMPTY: 'ROUTE_AGENT_ORDER_EMPTY',
  SUPERVISOR_LIVE_ORDERS_LIST: 'ROUTE_SUPERVISOR_LIVE_ORDERS_LIST',
  SUPERVISOR_LIVE_ORDER_DETAILS: 'ROUTE_SUPERVISOR_LIVE_ORDER_DETAILS',
  SUPERVISOR_LIVE_ORDER_EMPTY: 'ROUTE_SUPERVISOR_LIVE_ORDER_EMPTY',
  SUPERVISOR_ALL_ORDERS_LIST: 'ROUTE_SUPERVISOR_ALL_ORDERS_LIST',
  SUPERVISOR_ALL_ORDER_DETAILS: 'ROUTE_SUPERVISOR_ALL_ORDER_DETAILS',
  SUPERVISOR_BRANCHES_LIST: 'ROUTE_SUPERVISOR_BRANCHES_LIST',
  SUPERVISOR_BRANCH_CATALOGUES_LIST: 'ROUTE_SUPERVISOR_BRANCH_CATALOGUES_LIST',
  SUPERVISOR_BRANCH_CATALOGUE_DETAILS:
    'ROUTE_SUPERVISOR_BRANCH_CATALOGUE_DETAILS',
  SUPERVISOR_AGENTS_LIST: 'ROUTE_SUPERVISOR_AGENTS_LIST',
  SET_PASSWORD: 'ROUTE_SET_PASSWORD',
  SEND_RESET_PASSWORD_LINK: 'ROUTE_SEND_RESET_PASSWORD_LINK',
  RESET_PASSWORD: 'ROUTE_RESET_PASSWORD',
  RESEND_RESET_PASSWORD_LINK: 'ROUTE_RESEND_RESET_PASSWORD_LINK',
});
