export const USER_ROLES = {
  ACCOUNTANT: 'Accountant',
  APP_DESIGNER: 'AppDesigner',
  AREA_MANAGER: 'AreaManager',
  CATALOGUE_SUPERVISOR: 'CatalogueSupervisor',
  CATALOGUE_USER: 'CatalogueUser',
  CS_USER: 'CustomerService',
  FLEET_MANAGER: 'FleetManager',
  MARKETING_MANAGER: 'MarketingManager',
  MARKETING_USER: 'MarketingUser',
  OPS_MANAGER: 'OpsManager',
  OPS_USER: 'OpsUser',
  PILOT: 'Pilot',
  SUPER_ADMIN: 'SuperAdmin',
  VENDOR_BRANCH_USER: 'VendorBranchUser',
};

export const MAP_FEATURES = {
  TRAIL_PATH: 'trailPath',
  TRAIL_START: 'trailStart',
  TRAIL_END: 'trailEnd',
  PILOT: 'pilot',
  HUB: 'hub',
  LOCATION: 'location',
};

export const IMAGES = {
  mapMarkers: {
    BRANCH_LOCATION: `/consumer-assets/images/map-markers/branch-location-30.png`,
    DELIVERY_POINT: `/consumer-assets/images/map-markers/delivery-point-30.png`,
    ASSIGNMENT_LOCATION: `/consumer-assets/images/map-markers/assignment-location-30.png`,
    BRANCH_HUB: `/consumer-assets/images/map-markers/branch-hub-30.png`,
    PILOT_HUB: `/consumer-assets/images/map-markers/pilot-hub-30.png`,
    CUSTOMER_LOCATION: `/consumer-assets/images/map-markers/customer-location-30.png`,
    HUB: `/consumer-assets/images/map-markers/hub-30.png`,
    HUB_SELECTED: `/consumer-assets/images/map-markers/hub-selected-30.png`,
    NUMBERED_1: `/consumer-assets/images/map-markers/numbered-1-30.png`,
    NUMBERED_2: `/consumer-assets/images/map-markers/numbered-2-30.png`,
    NUMBERED_3: `/consumer-assets/images/map-markers/numbered-3-30.png`,
    NUMBERED_4: `/consumer-assets/images/map-markers/numbered-4-30.png`,
    NUMBERED_5: `/consumer-assets/images/map-markers/numbered-5-30.png`,
    NUMBERED_6: `/consumer-assets/images/map-markers/numbered-6-30.png`,
    NUMBERED_7: `/consumer-assets/images/map-markers/numbered-7-30.png`,
    NUMBERED_8: `/consumer-assets/images/map-markers/numbered-8-30.png`,
    NUMBERED_9: `/consumer-assets/images/map-markers/numbered-9-30.png`,
  },
  LOGO: `/consumer-assets/images/logo.png`,
  NOT_AVAILABLE: `/consumer-assets/images/image-not-available.png`,
  USER_FALLBACK: `/consumer-assets/images/no-profile.svg`,
  MAP_MARKER_GREEN: `/consumer-assets/images/map-marker-green.svg`,
  MAP_MARKER_RED: `/consumer-assets/images/map-marker-red.svg`,
  VENDOR_FALLBACK: `/consumer-assets/images/vendor.svg`,
  PILOT_MAP_MARKER: `/consumer-assets/images/vespa.png`,
  HUB_MAP_MARKER: `/consumer-assets/images/flag.svg`,
  FOOD_VENDOR: `https://images.pexels.com/photos/1633578/pexels-photo-1633578.jpeg`,
  COURIER_VENDOR: `https://images.unsplash.com/photo-1513672494107-cd9d848a383e?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80`,
  PHARMACY_VENDOR: `https://images.pexels.com/photos/159211/headache-pain-pills-medication-159211.jpeg`,
  PETS_VENDOR: `https://images.pexels.com/photos/1249208/pexels-photo-1249208.jpeg`,
  GROCERIES_VENDOR: `https://images.pexels.com/photos/64613/pexels-photo-64613.jpeg`,
  C2C_VENDOR: `https://images.unsplash.com/photo-1513672494107-cd9d848a383e?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80`,
  SURVV_SHOP_VENDOR: `https://images.unsplash.com/photo-1513672494107-cd9d848a383e?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80`,
};
