export const errors = {
  wrongCredentialsError: 'errors.wrong_credentials',
  imageLimitExceededError: 'errors.image_limit_exceeded',
  invalidImageTypeError: 'errors.invalid_image_type',
  unknownError: 'errors.unknown_error',
  processing: 'errors.processing',
  conflictError: 'errors.conflict_error',
  badRequestError: 'errors.bad_request',
  invalidInputTypeError: 'errors.invalid_input_type',
  missingPropError: 'errors.missing_prop_error',
  invalidFormError: 'errors.invalid_form',
  badFileError: 'errors.bad_file',
  badGeojsonError: 'errors.bad_geojson',
  noLinkableHubsError: 'errors.no_linkable_hubs',
  hydrationError: 'errors.hydration',
  invalidUrl: 'errors.invalid_url',

  // validation errors
  invalidEmailFormatError: 'ERR_INVALID_EMAIL_FORMAT',
  invalidPasswordError: 'validation.invalid.password',
  invalidMobileNumberError: 'validation.invalid.mobile_no',
  passwordMismatchError: 'validation.password_mismatch',
  missingEmailError: 'ERR_EMAIL_IS_REQUIRED',
  missingPasswordError: 'ERR_PASSWORD_IS_REQUIRED',
  missingMobileNumberError: 'validation.missing.mobile_number',
  missingFullNameError: 'validation.missing.full_name',
  missingRoleError: 'validation.missing.role',
  missingVendorLabelError: 'validation.missing.vendor_label',
  missingVendorBranchLabelError: 'validation.missing.vendor_branch_label',
  missingMaxTripTasksError: 'validation.missing.max_trip_tasks',
  invalidMaxTripTasksError: 'validation.invalid.max_trip_tasks',
  missingDateError: 'validation.missing.date',
  missingTimeError: 'validation.missing.time',
  missingContactPersonsError: 'validation.missing.contact_person',
  missingConfirmPassword: 'validation.missing.confirm_password',
  filterPilotMapLocationError: 'errors.filter_pilot_map_location_error',
  loadVendorsListError: 'errors.load_vendor_list_error',
  missingRushHours: 'validation.missing.rush_hour',
  missingRushHoursFrom: 'validation.missing.rush_hour_from',
  missingRushHoursTo: 'validation.missing.rush_hour_to',
  invalidTransPerHour: 'validation.invalid.avgTransPerHour',
  invalidTransPerDay: 'validation.invalid.avgTransPerDay',
  invalidTransPerMonth: 'validation.invalid.avgTransPerMonth',
  missingAddressData: 'validation.missing.address_data',
  missingNotesError: 'validation.missing.notes',
  missingStaffIdError: 'validation.missing.staff_id',
  invalidStaffIdError: 'validation.invalid.staff_id',
  missingAddressCountryError: 'validation.missing.address_country',
  missingAddressCityError: 'validation.missing.address_city',
  missingAddressAreaError: 'validation.missing.address_area',
  missingAddressStreetError: 'validation.missing.address_street',
  missingAddressBuildingError: 'validation.missing.address_building',
  missingVendorTypeError: 'validation.missing.vendor_type',
  missingCatalogueTitle: 'validation.missing.catalogue_title',
  missingZonesNames: 'validation.missing.zones_names',
  invalidMinTransactionsError: 'validation.invalid.min_transactions',
  invalidInitialMinTransactionsError:
    'validation.invalid.initial_min_transaction',
  invalidLastMaxTransactionsError: 'validation.invalid.last_max_transaction',
  maxLowerThanMinError: 'validation.invalid.max_lower_than_min',
  minGreaterThanMaxError: 'validation.invalid.min_greater_than_max',
  invalidPercentage: 'validation.invalid.percentage',
  expiryDateLowerThanEffectiveDate:
    'validation.invalid.expiry_lower_than_effective',

  // general
  missingImageError: 'validation.missing.image',
  missingFieldError: 'validation.missing.field',
  invalidNumberError: 'validation.invalid.number',
  invalidPositiveError: 'validation.invalid.positive',
  invalidMinMaxError: 'validation.invalid.min_max',
  LimitExceededError: 'validation.invalid.limit_exceeded',

  required: {
    cancellationNotes: 'validation.missing.cancellationNotes',
  },

  misc: {
    connection: 'errors.misc.connection',
    server: 'errors.misc.server',
    unknown: 'errors.misc.unknown',
  },

  survv: {
    NotFoundException: 'errors.survv.not_found',
    TaskAlreadyHasComplaintException:
      'errors.survv.task_already_has_complaint_exception',
    MobileNumberNotFoundException: 'errors.survv.customer_mobile_not_found',
    StaffIdAlreadyExistsException: 'errors.survv.staff_Id_exists',
    MobileNumberAlreadyExistsException: 'errors.survv.mobile_number_exists',
    FieldUpdateException: 'errors.survv.cannot_update_field',
    UserEmailAlreadyExistsException: 'errors.survv.user_email_exists',
    VendorLabelAlreadyReserved: 'errors.survv.vendor_label_exists',
    HubLabelAlreadyReserved: 'errors.survv.hub_label_exists',
    InactiveVendorException: 'errors.survv.inactive_vendor_exception',
    TrailNotReadyException: 'errors.survv.trail_not_ready',
    TransactionWriteConflictException: 'errors.survv.transaction_conflict',
    InconsistentCatalogueException: 'errors.survv.catalogue_validation_error',
    CatalogueTitleAlreadyExistsException: 'errors.survv.catalogue_title_exists',
    AreaNameAlreadyReserved: 'errors.survv.area_name_reserved',
    CityNameAlreadyReserved: 'errors.survv.city_name_reserved',
    InvalidCatalogueStatusException: 'errors.survv.catalogue_status',
    AreaZoneVersionNotConsistent:
      'errors.survv.zones_definition_version_mismatch',
    ZoneNamesAlreadyReserved: 'errors.survv.zone_names_reserved',
    InvalidBranchOrderFlagException: 'errors.survv.branch_online_ordering_flag',
    DateShouldBeInFutureException: 'errors.survv.date_not_in_future',
    NoBankDefinedException: 'errors.survv.no_defined_bank',
    PromotionOverlapException: 'errors.survv.promotion_overlap',
    YearCannotBeInPastException: 'errors.survv.years_in_past',
    NoPdfGeneratedForInvoiceException: 'errors.survv.no_invoice_pdf',
    VendorHasActiveBranchesException: 'errors.survv.vendor_branches_active',
    InvalidPhoneNumberException: 'errors.survv.invalid_phone_number',
  },
};
