module.exports = {
  'include': ['src/**/*.js', 'src/**/*.ts'],
  'exclude': [
    '**/*.nc.js',
    '**/*.nc.ts',
    '**/locales',
    '**/views',
    '**/components',
    '**/service-worker.*',
  ],
  'reporter': ['html', 'text'],
  'require': ['@survv/commons/babelRegister'],
  'instrument': false,
  'source-map': false,
  'clean': true,
  'cache': true,
  'eager': true,
  'check-coverage': true,
  'all': true,
  'per-file': true,
  'report-dir': 'coverage',
  'lines': 82,
  'statements': 82,
  'functions': 75,
  'branches': 50,
  'skip-full': true,
};
